export const avoResponses = [
    "Five ripe units, one spicy mission",
    "Our teamwork is smoother than fresh guac at brunch",
    "Guac hard or guac home",
    "Let's avo-go, team!",
    "Time to guac and roll!",
    "Let's slice through them like avo on a brunch menu.",
    "We're going full guac-tical ops now",
    "Guac N'Load",
    "They see green, they scream",
    "Our strats are fresher than a just-cut avocado",
    "They won't see us coming, just like an avocado in a salad",
    "Get ready to guac their world, team!",
    "Let's make this session smoother than guac on toast",
    "Our strategy is fresh, our aim is guac solid",
    "Show them the meaning of a Guac-18",
    "Time to mash them like a perfectly ripe avocado!",
    "Hold your positions, squad — it's time to guac-n-roll",
    "Let's slice through 'em like a knife through ripe avocados",
    "Team's fully ripe — time to drop in",
    "They're toast. We're the avocado",
    "Avocados never panic — we ripen under pressure",
    "Stay firm in the clutch, but soft where it counts",
    "Ripeness is a mindset. Go get 'em avos!",
    "Their defense? Soft. We're the only ones ripe today",
    "Stay ripe, stay deadly",
    "We're rich in nutrients... and firepower",
    "One team, one pit — unbreakable",
    "We're farm fresh and field ready",
    "Nothing artificial here — just straight organic precision",
    "We're packed with good fats and better strats",
    "Other teams spoil under pressure — we ripen in it",
    "We're the fruit of strategy, the seed of destruction",
    "Our teamwork is tighter than avo skin",
    "Ripe minds. Sharp blades. Clean plays",
    "You can't rush a good avocado. You can't rush us either",
    "We ripen together. We rise together",
    "Nothing artificial here — just clean, green kill streaks",
    "Pits primed. Pressure rising. Let's peel the map open",
    "They brought bullets. We brought botanical brutality",
    "Five avos. Five cores. One orchard of pain",
    "Our rotations are smooth like sliced halves — perfect symmetry",
    "We're not just ripe — we're ready to strike.",
    "Five units of fiber-rich destruction inbound",
    "These skins may be tough, but our plays are tougher",
    "Fully ripe and tactically terrifying",
    "You bring the salt, we bring the smash",
    "Avo-calypse now!",
    "This squad is ripe and reckless",
    "They play checkers — we play avocado chess",
    "Deploying flavor and firepower",
    "We're the final flavor they taste before defeat",
    "Our cooldown is as short as our shelf life"
]
